services:
  frontend:
    build: ./frontend
    container_name: rss-frontend
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://ec2-3-80-209-195.compute-1.amazonaws.com:4080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  api:
    build: ./api
    container_name: rss-api
    ports:
      - "4080:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
    volumes:
      - ./api:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: rss-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: